// Code generated by MockGen. DO NOT EDIT.
// Source: products_repository.go
//
// Generated by this command:
//
//	mockgen -source products_repository.go -destination mock/products_repository_mock.go -package repositoriesmock
//

// Package repositoriesmock is a generated GoMock package.
package repositoriesmock

import (
	context "context"
	reflect "reflect"

	models "github.com/zthiagovalle/demo-golang/src/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIProductsRepository is a mock of IProductsRepository interface.
type MockIProductsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIProductsRepositoryMockRecorder
	isgomock struct{}
}

// MockIProductsRepositoryMockRecorder is the mock recorder for MockIProductsRepository.
type MockIProductsRepositoryMockRecorder struct {
	mock *MockIProductsRepository
}

// NewMockIProductsRepository creates a new mock instance.
func NewMockIProductsRepository(ctrl *gomock.Controller) *MockIProductsRepository {
	mock := &MockIProductsRepository{ctrl: ctrl}
	mock.recorder = &MockIProductsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductsRepository) EXPECT() *MockIProductsRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIProductsRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIProductsRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIProductsRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockIProductsRepository) FindByID(ctx context.Context, id string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIProductsRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIProductsRepository)(nil).FindByID), ctx, id)
}

// Insert mocks base method.
func (m *MockIProductsRepository) Insert(ctx context.Context, p *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIProductsRepositoryMockRecorder) Insert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIProductsRepository)(nil).Insert), ctx, p)
}

// Paginate mocks base method.
func (m *MockIProductsRepository) Paginate(ctx context.Context, params *models.ProductPageParams) (*models.ProductPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paginate", ctx, params)
	ret0, _ := ret[0].(*models.ProductPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Paginate indicates an expected call of Paginate.
func (mr *MockIProductsRepositoryMockRecorder) Paginate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockIProductsRepository)(nil).Paginate), ctx, params)
}

// Update mocks base method.
func (m *MockIProductsRepository) Update(ctx context.Context, p *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIProductsRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIProductsRepository)(nil).Update), ctx, p)
}

// UpdateStatus mocks base method.
func (m *MockIProductsRepository) UpdateStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockIProductsRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockIProductsRepository)(nil).UpdateStatus), ctx, id, status)
}
