// Code generated by MockGen. DO NOT EDIT.
// Source: product_producer.go
//
// Generated by this command:
//
//	mockgen -source product_producer.go -destination mock/product_producer_mock.go -package producersmock
//

// Package producersmock is a generated GoMock package.
package producersmock

import (
	context "context"
	reflect "reflect"

	models "github.com/zthiagovalle/demo-golang/src/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIProductProducer is a mock of IProductProducer interface.
type MockIProductProducer struct {
	ctrl     *gomock.Controller
	recorder *MockIProductProducerMockRecorder
	isgomock struct{}
}

// MockIProductProducerMockRecorder is the mock recorder for MockIProductProducer.
type MockIProductProducerMockRecorder struct {
	mock *MockIProductProducer
}

// NewMockIProductProducer creates a new mock instance.
func NewMockIProductProducer(ctrl *gomock.Controller) *MockIProductProducer {
	mock := &MockIProductProducer{ctrl: ctrl}
	mock.recorder = &MockIProductProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductProducer) EXPECT() *MockIProductProducerMockRecorder {
	return m.recorder
}

// PublishCreated mocks base method.
func (m *MockIProductProducer) PublishCreated(ctx context.Context, p *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCreated", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCreated indicates an expected call of PublishCreated.
func (mr *MockIProductProducerMockRecorder) PublishCreated(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCreated", reflect.TypeOf((*MockIProductProducer)(nil).PublishCreated), ctx, p)
}
