// Code generated by MockGen. DO NOT EDIT.
// Source: create_product_usecase.go
//
// Generated by this command:
//
//	mockgen -source create_product_usecase.go -destination mock/create_product_usecase_mock.go -package usecasesmock
//

// Package usecasesmock is a generated GoMock package.
package usecasesmock

import (
	context "context"
	reflect "reflect"

	models "github.com/zthiagovalle/demo-golang/src/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockICreateProductUsecase is a mock of ICreateProductUsecase interface.
type MockICreateProductUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockICreateProductUsecaseMockRecorder
	isgomock struct{}
}

// MockICreateProductUsecaseMockRecorder is the mock recorder for MockICreateProductUsecase.
type MockICreateProductUsecaseMockRecorder struct {
	mock *MockICreateProductUsecase
}

// NewMockICreateProductUsecase creates a new mock instance.
func NewMockICreateProductUsecase(ctrl *gomock.Controller) *MockICreateProductUsecase {
	mock := &MockICreateProductUsecase{ctrl: ctrl}
	mock.recorder = &MockICreateProductUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreateProductUsecase) EXPECT() *MockICreateProductUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockICreateProductUsecase) Execute(ctx context.Context, input *models.ProductCreate) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockICreateProductUsecaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockICreateProductUsecase)(nil).Execute), ctx, input)
}
