// Code generated by MockGen. DO NOT EDIT.
// Source: delete_product_usecase.go
//
// Generated by this command:
//
//	mockgen -source delete_product_usecase.go -destination mock/delete_product_usecase_mock.go -package usecasesmock
//

// Package usecasesmock is a generated GoMock package.
package usecasesmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDeleteProductUsecase is a mock of IDeleteProductUsecase interface.
type MockIDeleteProductUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIDeleteProductUsecaseMockRecorder
	isgomock struct{}
}

// MockIDeleteProductUsecaseMockRecorder is the mock recorder for MockIDeleteProductUsecase.
type MockIDeleteProductUsecaseMockRecorder struct {
	mock *MockIDeleteProductUsecase
}

// NewMockIDeleteProductUsecase creates a new mock instance.
func NewMockIDeleteProductUsecase(ctrl *gomock.Controller) *MockIDeleteProductUsecase {
	mock := &MockIDeleteProductUsecase{ctrl: ctrl}
	mock.recorder = &MockIDeleteProductUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeleteProductUsecase) EXPECT() *MockIDeleteProductUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIDeleteProductUsecase) Execute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockIDeleteProductUsecaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIDeleteProductUsecase)(nil).Execute), ctx, id)
}
