// Code generated by MockGen. DO NOT EDIT.
// Source: get_all_paginated_products_usecase.go
//
// Generated by this command:
//
//	mockgen -source get_all_paginated_products_usecase.go -destination mock/get_all_paginated_products_usecase_mock.go -package usecasesmock
//

// Package usecasesmock is a generated GoMock package.
package usecasesmock

import (
	context "context"
	reflect "reflect"

	models "github.com/zthiagovalle/demo-golang/src/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIGetAllPaginatedProductsUsecase is a mock of IGetAllPaginatedProductsUsecase interface.
type MockIGetAllPaginatedProductsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIGetAllPaginatedProductsUsecaseMockRecorder
	isgomock struct{}
}

// MockIGetAllPaginatedProductsUsecaseMockRecorder is the mock recorder for MockIGetAllPaginatedProductsUsecase.
type MockIGetAllPaginatedProductsUsecaseMockRecorder struct {
	mock *MockIGetAllPaginatedProductsUsecase
}

// NewMockIGetAllPaginatedProductsUsecase creates a new mock instance.
func NewMockIGetAllPaginatedProductsUsecase(ctrl *gomock.Controller) *MockIGetAllPaginatedProductsUsecase {
	mock := &MockIGetAllPaginatedProductsUsecase{ctrl: ctrl}
	mock.recorder = &MockIGetAllPaginatedProductsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGetAllPaginatedProductsUsecase) EXPECT() *MockIGetAllPaginatedProductsUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIGetAllPaginatedProductsUsecase) Execute(ctx context.Context, params *models.ProductPageParams) (*models.ProductPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, params)
	ret0, _ := ret[0].(*models.ProductPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIGetAllPaginatedProductsUsecaseMockRecorder) Execute(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIGetAllPaginatedProductsUsecase)(nil).Execute), ctx, params)
}
