// Code generated by MockGen. DO NOT EDIT.
// Source: toggle_product_status_usecase.go
//
// Generated by this command:
//
//	mockgen -source toggle_product_status_usecase.go -destination mock/toggle_product_status_usecase_mock.go -package usecasesmock
//

// Package usecasesmock is a generated GoMock package.
package usecasesmock

import (
	context "context"
	reflect "reflect"

	models "github.com/zthiagovalle/demo-golang/src/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIToggleProductStatusUsecase is a mock of IToggleProductStatusUsecase interface.
type MockIToggleProductStatusUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIToggleProductStatusUsecaseMockRecorder
	isgomock struct{}
}

// MockIToggleProductStatusUsecaseMockRecorder is the mock recorder for MockIToggleProductStatusUsecase.
type MockIToggleProductStatusUsecaseMockRecorder struct {
	mock *MockIToggleProductStatusUsecase
}

// NewMockIToggleProductStatusUsecase creates a new mock instance.
func NewMockIToggleProductStatusUsecase(ctrl *gomock.Controller) *MockIToggleProductStatusUsecase {
	mock := &MockIToggleProductStatusUsecase{ctrl: ctrl}
	mock.recorder = &MockIToggleProductStatusUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToggleProductStatusUsecase) EXPECT() *MockIToggleProductStatusUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIToggleProductStatusUsecase) Execute(ctx context.Context, id string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIToggleProductStatusUsecaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIToggleProductStatusUsecase)(nil).Execute), ctx, id)
}
