// Code generated by MockGen. DO NOT EDIT.
// Source: update_product_usecase.go
//
// Generated by this command:
//
//	mockgen -source update_product_usecase.go -destination mock/update_product_usecase_mock.go -package usecasesmock
//

// Package usecasesmock is a generated GoMock package.
package usecasesmock

import (
	context "context"
	reflect "reflect"

	models "github.com/zthiagovalle/demo-golang/src/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIUpdateProductUsecase is a mock of IUpdateProductUsecase interface.
type MockIUpdateProductUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIUpdateProductUsecaseMockRecorder
	isgomock struct{}
}

// MockIUpdateProductUsecaseMockRecorder is the mock recorder for MockIUpdateProductUsecase.
type MockIUpdateProductUsecaseMockRecorder struct {
	mock *MockIUpdateProductUsecase
}

// NewMockIUpdateProductUsecase creates a new mock instance.
func NewMockIUpdateProductUsecase(ctrl *gomock.Controller) *MockIUpdateProductUsecase {
	mock := &MockIUpdateProductUsecase{ctrl: ctrl}
	mock.recorder = &MockIUpdateProductUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUpdateProductUsecase) EXPECT() *MockIUpdateProductUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIUpdateProductUsecase) Execute(ctx context.Context, id string, input *models.ProductUpdate) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id, input)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIUpdateProductUsecaseMockRecorder) Execute(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIUpdateProductUsecase)(nil).Execute), ctx, id, input)
}
